In [5]:
import numpy as np
import pandas as pd
import pickle

INPUT = "code/dataset/Original/global/global-genre_network-2019.csv"
df = pd.read_csv(INPUT, sep="\t")


genres = pd.unique(df[["source", "target"]].values.ravel())
genre_to_idx = {g: i for i, g in enumerate(genres)}
n = len(genres)

i = df["source"].map(genre_to_idx).to_numpy()
j = df["target"].map(genre_to_idx).to_numpy()
w = df["weight"].to_numpy()

adj_numpy = np.zeros((n, n), dtype=np.float32)

for a, b, val in zip(i, j, w):
    adj_numpy[a, b] = max(adj_numpy[a, b], val)
    adj_numpy[b, a] = max(adj_numpy[b, a], val)

#check properties
is_symmetric = np.allclose(adj_numpy, adj_numpy.T)
density = np.count_nonzero(adj_numpy) / adj_numpy.size

print("Symmetric:", is_symmetric)
print("Density:", density)


np.save("my_graph.npy", adj_numpy)
pickle.dump(genres.tolist(), open("matrix_vocab.pkl", "wb"))

Symmetric: True
Density: 0.06016649323621228


In [6]:
print(adj_numpy)

[[282. 479.  24. ...   0.   0.   0.]
 [479. 197.  22. ...   0.   0.   0.]
 [ 24.  22.  73. ...   0.   0.   0.]
 ...
 [  0.   0.   0. ...   0.   0.   0.]
 [  0.   0.   0. ...   0.   0.   0.]
 [  0.   0.   0. ...   0.   0.   0.]]
